//! `NEXUS_MEMORY.md` — the project-memory document as a BUILD PRODUCT (6j6v.8q88).
//!
//! Since the reach of a memory decides where it surfaces (6j6v.srpg), everything a hand-maintained
//! context document used to hold is simply a memory with reach `project`. So the document stops
//! being a source and becomes a **projection**: `nxm` is the one source of truth, this file is its
//! rendering, and git supplies the version history the store does not have — with the diff visible
//! in the change proposal. The precedent is `AGENTS.md`, already a generated context file nobody
//! may edit by hand; this carries the pattern to its end.
//!
//! Two readers justify the file's existence, and both explain its shape:
//!
//! * A contributor with no nexus-flow installed. Exactly one wired SessionStart hook carries a
//!   `|| cat NEXUS_MEMORY.md` tail (the first the assembler wires — Ruling R1, nxf a2a1), so this
//!   file is the fallback path. *(It was a single `nxs prime || cat NEXUS_MEMORY.md` hook until
//!   nxf n2m6 + a2a1 split the wiring one-per-module; the tail moved onto the first entry rather
//!   than onto all of them, so the file still arrives exactly once.)*
//! * Somebody reading the repository on a forge, where no hook runs at all.
//!
//! **Two halves since 6j6v.xbnh, and the notice between them is the point** (owner decision of
//! 2026-08-27). The file opens with the SAME index `nxm prime` replays, under a notice saying that
//! this half is already in the session's context — because the incident that opened that ticket was
//! an agent reading this file top to bottom while `nxs prime` sat in the SessionStart hook. Below
//! the notice the full bodies remain, and that is deliberate too: the file is the versioned,
//! diff-able record of what the memories SAY, so a change to a memory stays visible in a change
//! proposal. An index-only file would move every body into sqlite alone and out of every diff.
//!
//! The index half is therefore a strict subset of `prime` (it is the same renderer over the same
//! set); the full-text half is what `nxm recall <key>` serves, and the notice tells a reader to
//! read it the same way — one memory at a time, on purpose.
//!
//! **Generation is a side effect of writing, never a command someone must remember to run**
//! ([`regenerate`]): every `nxm` write regenerates it, and so does a sync pass that pulled new ops
//! (`nxs sync daemon`). Deliberately NOT at `prime`: a session start only heals the file once
//! somebody opens the project, so a repository resting for two weeks would show a two-week-old
//! state to precisely the reader the file exists for. `prime` itself reads `nxm` directly and is
//! never stale.
//!
//! Because a background daemon now writes a VERSIONED file inside somebody else's git worktree
//! while they work in it, [`regenerate`] holds three rules: write only when the content actually
//! differs (so the normal case is no write at all), never commit (the change is unstaged and
//! belongs to the human), and stand down entirely while the worktree is mid-operation — a rebase,
//! a merge, a conflict resolution ([`git_operation_in_progress`]).

use crate::error::{NxfError, Result};
use crate::facade;
use crate::store::MemoryStore;
use std::path::{Path, PathBuf};

/// The generated file's name, at the workspace root (next to `AGENTS.md`, the other generated
/// context file).
pub const FILE_NAME: &str = "NEXUS_MEMORY.md";

/// The header every generated copy carries. Two audiences, deliberately: the HTML comment marks the
/// file as managed for a tool or a reviewer skimming the diff, and the visible blockquote tells a
/// human who opened it on a forge where the text really comes from and how to change it. Without
/// the second one the file looks like ordinary documentation, somebody edits it, and source and
/// projection drift — the same failure class as a frozen copy whose header still claims to be
/// interim four releases later.
const HEADER: &str = "<!-- generated by nexus-flow — do not edit; run `nxm remember` instead -->\n\
                      # Project memory\n\n\
                      > **Generated file — do not edit.** Every entry below is a memory in this \
                      project's `nxm` store, projected here so the context survives without \
                      nexus-flow installed. Change it with `nxm remember` / `nxm forget`; an edit \
                      made here is overwritten by the next write. `nxm doc --check` reports drift.";

/// The notice that separates the two halves, and the reason the file is not simply read top to
/// bottom (6j6v.xbnh).
///
/// It is the direct answer to the incident that opened that ticket: an agent whose SessionStart
/// hook had ALREADY delivered the index opened this file and read all of it by hand. A notice that
/// only said "this is generated" would not have stopped it — what stops it is naming which half it
/// already has and how the other half is meant to be read.
///
/// **Corrected 2026-08-28 (nxf n2m6 + a2a1): it named `nxs prime`.** The notice said the index was
/// "the same one `nxs prime` replays at session start", which was exact while `nxs prime` WAS the
/// SessionStart hook. It is one hook per active module now, so what replays this index at session
/// start is `nxm prime`; `nxs prime` still replays it when a person runs that verb by hand. The
/// point of the sentence is to tell the reader they already hold this — naming a command that no
/// longer runs at session start would undercut exactly that.
///
/// **Corrected 2026-08-29 (nxf 6j6v.5jm3): "the same one" became conditionally false.** The block's
/// index is bounded now ([`facade::PRIME_BLOCK_BUDGET_BYTES`]) while this document's is not — it is
/// the versioned record of what the workspace knows, and a record that dropped entries to fit a
/// host's hook limit would be a worse artifact, not a smaller one. So in a large workspace the two
/// indexes genuinely differ, and a notice claiming they are the same would send a reader past
/// exactly the lines a session start could not hand them.
///
/// The sentence therefore states the relationship rather than an equality — you hold all of it or
/// its leading part — and names `nxm index`, which is the other place the whole of it is served.
/// Both halves of the notice's job survive: it still says which half the reader already has, and it
/// still says the full text below is read one memory at a time.
const READ_ME_FIRST: &str =
    "> **You have already been given the index below** — all of it, or as much of it as a session \
     start could carry. It is the same index `nxm prime` replays, which stops at the byte budget \
     the host delivers and says so when it does (`nxm index` prints the whole of it), so there is \
     nothing to gain by reading it again here. Underneath it stands the FULL TEXT of each memory — \
     that is what `nxm recall <key>` serves, and it is meant to be read one memory at a time, when \
     the index tells you a particular one matters. Reading this file end to end is the expensive \
     way to obtain what you already have.";

/// What [`regenerate`] did — a value rather than a printed line, because the callers differ wildly:
/// the CLI stays silent (the file shows up in `git status`), the sync daemon logs, and a test
/// asserts.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// The file was created or rewritten (the content genuinely changed).
    Written(PathBuf),
    /// The file is already byte-identical to the projection — the steady state, and the common
    /// case for a daemon pass.
    Unchanged(PathBuf),
    /// Nothing was written, and why. Never an error: each reason is a legitimate state.
    Skipped(Skip),
}

/// Why [`regenerate`] wrote nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Skip {
    /// There is no file yet and no memory to project into one. A workspace that has never
    /// remembered anything does not get an empty document planted in its root; once the file
    /// EXISTS it is kept accurate, empty state included, so it can never quietly lie.
    NothingToProject,
    /// The git worktree is mid-operation (the named one: `rebase`, `merge`, …). Writing an
    /// unrelated file into a worktree somebody is rebasing is how a background process turns a
    /// tricky moment into a confusing one.
    WorktreeBusy(&'static str),
}

/// Render the projection for `store` — the exact bytes the file should hold.
///
/// Both halves come from `prime`'s own set and `prime`'s own renderers, so neither can drift from
/// the session start: the index is [`facade::render_memory_index`] (byte for byte what a session is
/// handed) and the full text below it is [`facade::render_memory_blocks`]. Item-scoped memories that
/// name board items are left out here for the same reason they are left out of `prime` — they read
/// where a reader is already looking.
pub fn render(store: &MemoryStore) -> Result<String> {
    let report = facade::prime(store)?;
    Ok(render_report(&report))
}

/// [`render`] over an already-computed report — the pure half, so a caller that already holds a
/// [`PrimeReport`](facade::PrimeReport) (the subset proof, for one) does not read the store twice.
pub fn render_report(report: &facade::PrimeReport) -> String {
    format!("{HEADER}\n\n{}\n", body_of(report))
}

/// The part of the document that comes from the store: the index, the notice, and the full bodies
/// beneath — or `prime`'s own empty-state sentence when there is nothing to project (6j6v.xbnh).
///
/// The two halves are separated by a heading rather than only by prose, so a reader skimming the
/// outline sees where the index stops and the full text begins.
fn body_of(report: &facade::PrimeReport) -> String {
    if report.memories.is_empty() {
        return facade::PRIME_NO_MEMORIES.to_string();
    }
    let mut parts = vec![
        READ_ME_FIRST.to_string(),
        format!("## Index ({})", report.memories.len()),
        facade::render_memory_index(&report.memories),
    ];
    parts.extend(report.introduction_gap());
    parts.push("## Full text".to_string());
    parts.push(facade::render_memory_blocks(&report.memories));
    parts.join("\n\n")
}

/// Regenerate `<root>/NEXUS_MEMORY.md` from `store`. The one write path — every trigger (an `nxm`
/// write, a sync pass that pulled ops) calls exactly this, so the three worktree rules cannot be
/// implemented twice and drift apart.
///
/// Never fails just because there is nothing to do: a no-op is an [`Outcome`], not an error. A
/// genuine IO failure IS an error, because a file this one silently failed to write is precisely
/// the stale context the drift check exists to catch.
pub fn regenerate(store: &MemoryStore, root: &Path) -> Result<Outcome> {
    let path = root.join(FILE_NAME);
    let current = match std::fs::read_to_string(&path) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            return Err(NxfError::io(format!(
                "reading {} to compare it with the memory store: {e}",
                path.display()
            )))
        }
    };
    // ONE read of the store per call (PR #287 review, Code Quality #1): the report answers both
    // "what should the file say" and "is there anything to say at all", and this path runs on every
    // single memory write.
    let report = facade::prime(store)?;
    let target = render_report(&report);

    // An untouched workspace stays untouched: no file and nothing to say means no file.
    if current.is_none() && report.memories.is_empty() {
        return Ok(Outcome::Skipped(Skip::NothingToProject));
    }
    // The normal case, checked BEFORE the worktree guard on purpose: when nothing changed there is
    // nothing to suspend, and reporting `Unchanged` during a rebase is more truthful than
    // reporting that a write was held back.
    if current.as_deref() == Some(target.as_str()) {
        return Ok(Outcome::Unchanged(path));
    }
    if let Some(op) = git_operation_in_progress(root) {
        return Ok(Outcome::Skipped(Skip::WorktreeBusy(op)));
    }

    write_atomic(&path, target.as_bytes())?;
    Ok(Outcome::Written(path))
}

/// How the file on disk compares with the store — what `nxm doc --check` reports.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Drift {
    /// The file matches the projection byte for byte.
    InSync,
    /// The file exists and does NOT match: it was edited by hand, or a write that should have
    /// regenerated it never ran (a daemon that was not running here is exactly this case, which is
    /// what turns that failure from silent into loud).
    Drifted,
    /// The store has memories to project but no file exists.
    Missing,
    /// No file, and nothing to project into one — the untouched workspace, in sync trivially.
    NotApplicable,
}

impl Drift {
    /// Whether this is a state the check should go red on.
    pub fn is_drift(&self) -> bool {
        matches!(self, Drift::Drifted | Drift::Missing)
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Drift::InSync => "in_sync",
            Drift::Drifted => "drifted",
            Drift::Missing => "missing",
            Drift::NotApplicable => "not_applicable",
        }
    }
}

/// Compare `<root>/NEXUS_MEMORY.md` with the projection of `store`, without writing anything.
pub fn check(store: &MemoryStore, root: &Path) -> Result<Drift> {
    let path = root.join(FILE_NAME);
    // One read of the store here too — same reason as in [`regenerate`].
    let report = facade::prime(store)?;
    let target = render_report(&report);
    match std::fs::read_to_string(&path) {
        Ok(current) if current == target => Ok(Drift::InSync),
        Ok(_) => Ok(Drift::Drifted),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            if report.memories.is_empty() {
                Ok(Drift::NotApplicable)
            } else {
                Ok(Drift::Missing)
            }
        }
        Err(e) => Err(NxfError::io(format!(
            "reading {} to compare it with the memory store: {e}",
            path.display()
        ))),
    }
}

// ---- the git worktree guard -------------------------------------------------------------------

/// The mid-operation markers git leaves in the gitdir, each with the name to report. Order is
/// report order only — any one of them means "stand down".
const GIT_OPERATIONS: &[(&str, &str)] = &[
    ("rebase-merge", "rebase"),
    ("rebase-apply", "rebase"),
    ("MERGE_HEAD", "merge"),
    ("CHERRY_PICK_HEAD", "cherry-pick"),
    ("REVERT_HEAD", "revert"),
    ("BISECT_LOG", "bisect"),
];

/// The operation `root`'s git worktree is in the middle of, or `None` when it is idle (or is not a
/// git worktree at all — an unversioned workspace has nothing to protect).
///
/// Reads the markers directly instead of shelling out to `git`: the check runs on every memory
/// write and on every daemon pass, the marker layout is git's own stable on-disk contract, and a
/// file-based check is testable without a git binary. The `.git` entry is followed when it is a
/// FILE (`gitdir: …`) rather than a directory, which is the linked-worktree and submodule case —
/// and precisely the case that matters, since each linked worktree keeps its OWN rebase/merge
/// state in its own gitdir.
pub fn git_operation_in_progress(root: &Path) -> Option<&'static str> {
    let git_dir = resolve_git_dir(root)?;
    GIT_OPERATIONS
        .iter()
        .find(|(marker, _)| git_dir.join(marker).exists())
        .map(|(_, name)| *name)
}

/// The gitdir for the worktree at `root`: `<root>/.git` when that is a directory, else the path its
/// `gitdir: <path>` pointer names (relative paths resolve against `root`, as git writes them).
fn resolve_git_dir(root: &Path) -> Option<PathBuf> {
    let dot_git = root.join(".git");
    if dot_git.is_dir() {
        return Some(dot_git);
    }
    let pointer = std::fs::read_to_string(&dot_git).ok()?;
    let target = pointer
        .lines()
        .find_map(|l| l.trim().strip_prefix("gitdir:"))?;
    let target = Path::new(target.trim());
    Some(if target.is_absolute() {
        target.to_path_buf()
    } else {
        root.join(target)
    })
}

// ---- the atomic writer ------------------------------------------------------------------------

/// Write `contents` to `path` atomically: a sibling temp opened `O_EXCL`, then a same-directory
/// rename over the target. Two reasons, both real here: a reader (an agent whose SessionStart hook
/// just `cat`ted this file) never sees a half-written document, and a symlink squatting on the
/// PREDICTABLE temp path is refused rather than followed.
///
/// A local copy of the idiom `nxs`'s registry/heartbeat writers use, because theirs is
/// `pub(crate)` in another crate. Kept deliberately short and identical in shape so the two read as
/// the same routine.
fn write_atomic(path: &Path, contents: &[u8]) -> Result<()> {
    use std::io::Write as _;
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let name = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or(FILE_NAME);
    let tmp = dir.join(format!(".{name}.nxm.tmp.{}", std::process::id()));
    let write = || -> std::io::Result<()> {
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&tmp)?;
        f.write_all(contents)?;
        f.sync_all()
    };
    write()
        .and_then(|()| std::fs::rename(&tmp, path))
        .map_err(|e| {
            let _ = std::fs::remove_file(&tmp); // best-effort: never strand the temp sibling
            NxfError::io(format!("writing {}: {e}", path.display()))
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::facade::Classification;
    use crate::model::Scope;
    use tempfile::TempDir;

    const NOW: &str = "2026-08-04T10:00:00Z";

    fn store() -> MemoryStore {
        MemoryStore::open_in_memory(1)
    }

    /// `remember` with the introduction these tests are not about — `remember` requires one
    /// (6j6v.xbnh), so the fixtures say it once here rather than at every call.
    fn remember(s: &mut MemoryStore, key: &str, body: &str) {
        let class = Classification {
            introduction: Some(format!("what `{key}` says, in one line")),
            ..Classification::default()
        };
        facade::remember(s, NOW, "alice", Some(key), body, &class).unwrap();
    }

    // ---- the document itself --------------------------------------------------------------

    #[test]
    fn the_document_names_itself_a_build_product_and_says_how_to_change_it() {
        // Rule (a): without this the file reads as ordinary documentation, and the first person to
        // improve a sentence in it has silently forked the source.
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        let doc = render(&s).unwrap();
        assert!(doc.starts_with("<!-- generated by nexus-flow"), "{doc}");
        assert!(doc.contains("do not edit"), "{doc}");
        assert!(doc.contains("nxm remember"), "{doc}");
        assert!(doc.contains("auth uses JWT, not sessions"), "{doc}");
    }

    #[test]
    fn the_document_carries_the_same_memories_in_the_same_order_as_prime() {
        // **This was a byte-for-byte SUBSET condition until nxf 6j6v.waq9, and the change is
        // deliberate.** The document and the session-start block answer two different questions:
        // the document is the whole of what this workspace knows, read by an agent whose host runs
        // no hooks, while `prime` is what EVERY session pays for at its start and is an index only.
        // A whole-document substring assertion would now be an assertion that the saving does not
        // exist.
        //
        // What must still hold — and what is asserted here — is the trio the subset condition was
        // standing in for:
        //
        // 1. **The same memory SET.** Both are rendered from `prime`'s own memory set, so a memory
        //    the retrieval rule withholds (an `item`-scoped one filed against board items) is
        //    absent from both, and nothing the document names is unreachable from the block.
        // 2. **The same ORDER** (6j6v.643z). Once two documents order their memories, drift means
        //    two different sequences of the same entries. The set below is deliberately FILED so
        //    category, position and reach are all represented.
        // 3. **The same INDEX, byte for byte** (6j6v.xbnh) — the half the file's notice claims the
        //    reader already has. If the two indexes could differ, the notice would be a lie.
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        remember(&mut s, "race", "always run the tests with -race");
        facade::remember(
            &mut s,
            NOW,
            "alice",
            Some("global"),
            "never rewrite a published tag",
            &Classification {
                scope: Some(Scope::Global),
                introduction: Some("never rewrite a tag that is already published".into()),
                ..Default::default()
            },
        )
        .unwrap();
        facade::classify(
            &mut s,
            NOW,
            "alice",
            "race",
            &Classification {
                category: Some("build-test".into()),
                ..Default::default()
            },
        )
        .unwrap();
        facade::classify(
            &mut s,
            NOW,
            "alice",
            "global",
            &Classification {
                category: Some("introduction".into()),
                ..Default::default()
            },
        )
        .unwrap();
        facade::reorder(&mut s, NOW, "alice", &["global".to_string()]).unwrap();

        let report = facade::prime(&s).unwrap();
        let body = body_of(&report);
        let block = report.render_markdown();
        // (1) the same set, each memory reachable from the block — whole for a rule, by key for the
        // rest — so nothing the document names has gone missing from the session start.
        //
        // **Corrected 2026-08-28 (nxf q065, task 4).** This used to check for `` `{key}` `` —
        // backtick-quoted, not the `` **{key}** `` (bold) `render_memory_index` actually emits — so
        // it never tested what it says it tests, and passed on two unrelated accidents at once.
        // MEASURED against the rendered block rather than reasoned about, because the first attempt
        // at this note named only one of them:
        //
        // * `auth` and `race` are written by this module's own `remember` helper, whose
        //   introduction template is `format!("what `{key}` says, in one line")`. The index line
        //   therefore CONTAINS the backticked key, inside the introduction — so the old assertion
        //   matched the fixture's own boilerplate, and still would today.
        // * `global` is written by the `facade::remember` call just above, with an introduction
        //   that never names its key. It matched the pre-task-4 "## Memory Commands" section
        //   instead: the `nxm classify` entry's summary reads "…(reach `project`/`global` keeps
        //   reading here)". Task 4 drops that entry from the human view (see
        //   `PrimeReport::render_markdown`'s doc comment), and `` `global` `` is now absent from
        //   the block — which is what made the old assertion fail and exposed the rest.
        //
        // Neither accident is the property this assertion means to check, so it is corrected to the
        // format the index actually renders, matching (2)/(3) below.
        for m in &report.memories {
            assert!(
                block.contains(&format!("**{}**", m.key)),
                "the block must still name **{}**:\n{block}",
                m.key
            );
        }
        // (2) the same order. The document renders the index and the block renders the index, from
        // one set through one renderer, so the sequence is now assertable GLOBALLY again — the
        // per-class statement this used to make was a consequence of the two-class split that
        // 6j6v.xbnh removed.
        let in_document: Vec<usize> = report
            .memories
            .iter()
            .map(|m| body.find(&format!("**{}**", m.key)).expect("indexed"))
            .collect();
        let in_block: Vec<usize> = report
            .memories
            .iter()
            .map(|m| block.find(&format!("**{}**", m.key)).expect("indexed"))
            .collect();
        assert!(
            in_document.windows(2).all(|w| w[0] < w[1]) && in_block.windows(2).all(|w| w[0] < w[1]),
            "document order and block order must not fork:\n--- document ---\n{body}\n\
             --- block ---\n{block}"
        );
        // (3) the index half is `prime`'s own bytes, so the file cannot show a DIFFERENT index
        // from the one the session already has — the promise the notice above it makes.
        //
        // **Narrowed 2026-08-29 (nxf 6j6v.5jm3): the block's index is a PREFIX of the file's, not
        // necessarily the whole of it.** The block stops at its byte budget and the file does not,
        // so "byte for byte" is only the small-workspace case — which is this fixture, and is
        // asserted as such below. The relationship that holds at every size is the prefix one, and
        // `the_document_keeps_every_line_a_cut_block_had_to_drop` covers the other side.
        let whole_index = facade::render_memory_index(&report.memories);
        assert!(
            body.contains(&whole_index),
            "the file's index is the whole index:\n{body}"
        );
        assert!(
            block.contains(&whole_index),
            "and at this size the block carries all of it, byte for byte:\n{block}"
        );
        assert!(
            body.contains("## Full text\n\n### `global`"),
            "and the full-text half is in reading order, not by key:\n{body}"
        );
    }

    #[test]
    fn the_document_keeps_every_line_a_cut_block_had_to_drop() {
        // nxf 6j6v.5jm3, the other side of the subset proof. The block is bounded by the host's
        // hook limit; this file is not, because it is the versioned record of what the workspace
        // knows and is read on demand rather than injected. So the document is where the lines a
        // session start could not carry still stand — and the notice at its head has to be true of
        // exactly that arrangement.
        let mut s = store();
        for i in 0..70 {
            let head = format!("memory {i:03}: ");
            let introduction = format!(
                "{head}{}",
                "x".repeat(crate::model::INTRODUCTION_MAX_CHARS - head.chars().count())
            );
            facade::remember(
                &mut s,
                NOW,
                "alice",
                Some(&format!("memory-{i:03}")),
                "a body",
                &Classification {
                    introduction: Some(introduction),
                    category: Some("architecture".into()),
                    ..Default::default()
                },
            )
            .unwrap();
        }

        let report = facade::prime(&s).unwrap();
        let body = body_of(&report);
        let block = report.render_markdown();

        let listed = |text: &str| text.matches("\n- **memory-").count();
        assert!(
            listed(&block) < 70,
            "this fixture exists to make the block cut, and it listed all {}",
            listed(&block)
        );
        assert_eq!(listed(&body), 70, "the document lists every one of them");
        assert!(body.contains("## Index (70)"));

        // Every memory the block dropped is still here, in full — head and body.
        for i in listed(&block)..70 {
            let key = format!("memory-{i:03}");
            assert!(
                !block.contains(&format!("**{key}**")),
                "{key} is past the block's budget"
            );
            assert!(
                body.contains(&format!("### `{key}`")),
                "{key} keeps its full text in the document:\n{body}"
            );
        }

        // And the notice's promise reads true against BOTH: it claims the leading part, not equality.
        assert!(
            READ_ME_FIRST.contains("all of it, or as much of it as a session start could carry")
        );
        assert!(READ_ME_FIRST.contains("`nxm index`"));
    }

    #[test]
    fn an_item_scoped_memory_about_a_board_item_stays_out_of_the_document() {
        // It reads on the board item instead (the retrieval rule), so replaying it here would be
        // the very drowning-in-detail `prime` avoids — and would break the subset property too.
        let mut s = store();
        remember(&mut s, "everywhere", "the shared rule");
        facade::remember(
            &mut s,
            NOW,
            "alice",
            Some("about-a-ticket"),
            "this one detail concerns 6j6v.8q88 only",
            &Classification {
                scope: Some(Scope::Item),
                refs: Some(vec!["6j6v.8q88".into()]),
                introduction: Some("one detail that belongs to 6j6v.8q88 alone".into()),
                ..Default::default()
            },
        )
        .unwrap();

        let doc = render(&s).unwrap();
        assert!(doc.contains("the shared rule"));
        assert!(!doc.contains("this one detail"), "{doc}");
    }

    // ---- the write rule -------------------------------------------------------------------

    #[test]
    fn a_write_creates_the_file_and_a_second_pass_leaves_it_alone() {
        // "Only write when the content actually differs" — the rule that makes a background
        // process writing into somebody's worktree tolerable: in the steady state it does nothing.
        let tmp = TempDir::new().unwrap();
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");

        let path = tmp.path().join(FILE_NAME);
        assert_eq!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(path.clone())
        );
        let written = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Unchanged(path.clone())
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), written);
    }

    #[test]
    fn an_empty_store_gets_no_file_planted_in_its_root() {
        let tmp = TempDir::new().unwrap();
        let s = store();
        assert_eq!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Skipped(Skip::NothingToProject)
        );
        assert!(!tmp.path().join(FILE_NAME).exists());
    }

    #[test]
    fn an_existing_file_is_kept_accurate_even_once_the_last_memory_is_forgotten() {
        // The other half of the rule above: not creating a file is a courtesy, but leaving a
        // STALE one behind would be the lie the whole ticket is about.
        let tmp = TempDir::new().unwrap();
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        regenerate(&s, tmp.path()).unwrap();
        facade::forget(&mut s, NOW, "alice", "auth").unwrap();

        assert!(matches!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(_)
        ));
        let doc = std::fs::read_to_string(tmp.path().join(FILE_NAME)).unwrap();
        assert!(!doc.contains("auth uses JWT"), "{doc}");
    }

    #[test]
    fn a_hand_edit_is_detected_and_then_healed_by_the_next_write() {
        let tmp = TempDir::new().unwrap();
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        regenerate(&s, tmp.path()).unwrap();

        std::fs::write(
            tmp.path().join(FILE_NAME),
            "# Project memory\n\nsomething a human typed\n",
        )
        .unwrap();
        assert_eq!(check(&s, tmp.path()).unwrap(), Drift::Drifted);
        assert!(check(&s, tmp.path()).unwrap().is_drift());

        assert!(matches!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(_)
        ));
        assert_eq!(check(&s, tmp.path()).unwrap(), Drift::InSync);
    }

    #[test]
    fn a_missing_file_with_memories_to_project_is_drift_but_an_empty_workspace_is_not() {
        let tmp = TempDir::new().unwrap();
        let mut s = store();
        assert_eq!(check(&s, tmp.path()).unwrap(), Drift::NotApplicable);
        assert!(!check(&s, tmp.path()).unwrap().is_drift());

        remember(&mut s, "auth", "auth uses JWT, not sessions");
        assert_eq!(check(&s, tmp.path()).unwrap(), Drift::Missing);
        assert!(check(&s, tmp.path()).unwrap().is_drift());
    }

    // ---- the worktree guard ---------------------------------------------------------------

    /// A worktree whose `.git` is a real directory (the ordinary clone).
    fn git_worktree(root: &Path) -> PathBuf {
        let git = root.join(".git");
        std::fs::create_dir_all(&git).unwrap();
        git
    }

    #[test]
    fn a_worktree_in_the_middle_of_an_operation_is_left_alone() {
        // Rule (c): a background daemon must not drop an unrelated file into a worktree somebody
        // is rebasing. Table-driven over every marker, since missing ONE of them is the whole risk.
        for (marker, name) in GIT_OPERATIONS {
            let tmp = TempDir::new().unwrap();
            let git = git_worktree(tmp.path());
            let mut s = store();
            remember(&mut s, "auth", "auth uses JWT, not sessions");

            // Directory markers (`rebase-merge/`) and file markers (`MERGE_HEAD`) both exist; a
            // directory works for either, since the guard only asks whether the path is there.
            std::fs::create_dir_all(git.join(marker)).unwrap();

            assert_eq!(
                regenerate(&s, tmp.path()).unwrap(),
                Outcome::Skipped(Skip::WorktreeBusy(name)),
                "{marker} must hold the write back"
            );
            assert!(
                !tmp.path().join(FILE_NAME).exists(),
                "{marker}: nothing was written"
            );
        }
    }

    #[test]
    fn an_idle_worktree_is_written_to_normally() {
        let tmp = TempDir::new().unwrap();
        git_worktree(tmp.path());
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        assert!(matches!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(_)
        ));
    }

    #[test]
    fn a_linked_worktree_is_read_through_its_gitdir_pointer() {
        // `git worktree add` writes `.git` as a FILE pointing at the per-worktree gitdir, and that
        // is where ITS rebase state lives. Following the pointer is what makes the guard work in
        // the setup this project itself uses for parallel branches.
        let tmp = TempDir::new().unwrap();
        let real_git = tmp.path().join("main-checkout/.git/worktrees/feature");
        std::fs::create_dir_all(real_git.join("rebase-merge")).unwrap();
        let linked = tmp.path().join("linked");
        std::fs::create_dir_all(&linked).unwrap();
        std::fs::write(
            linked.join(".git"),
            format!("gitdir: {}\n", real_git.display()),
        )
        .unwrap();

        assert_eq!(git_operation_in_progress(&linked), Some("rebase"));
    }

    #[test]
    fn a_workspace_that_is_not_a_git_worktree_at_all_has_nothing_to_stand_down_for() {
        let tmp = TempDir::new().unwrap();
        assert_eq!(git_operation_in_progress(tmp.path()), None);
    }

    #[test]
    fn a_content_change_during_a_rebase_is_held_back_and_lands_after_it() {
        let tmp = TempDir::new().unwrap();
        let git = git_worktree(tmp.path());
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        regenerate(&s, tmp.path()).unwrap();

        std::fs::create_dir_all(git.join("rebase-merge")).unwrap();
        remember(&mut s, "race", "always run the tests with -race");
        assert_eq!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Skipped(Skip::WorktreeBusy("rebase"))
        );
        assert!(!std::fs::read_to_string(tmp.path().join(FILE_NAME))
            .unwrap()
            .contains("-race"));

        std::fs::remove_dir_all(git.join("rebase-merge")).unwrap();
        assert!(matches!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(_)
        ));
        assert!(std::fs::read_to_string(tmp.path().join(FILE_NAME))
            .unwrap()
            .contains("-race"));
    }

    #[test]
    fn an_unchanged_document_reports_unchanged_even_mid_rebase() {
        // PR #287 review, Test Quality #3: the order of the two guards is a deliberate claim —
        // "nothing changed" is checked BEFORE "the worktree is busy", because when there is
        // nothing to write there is nothing to hold back, and `Unchanged` is the truthful answer.
        // Without this pairing the ordering could silently invert and no test would notice.
        let tmp = TempDir::new().unwrap();
        let git = git_worktree(tmp.path());
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        let path = match regenerate(&s, tmp.path()).unwrap() {
            Outcome::Written(p) => p,
            other => panic!("expected the first write, got {other:?}"),
        };

        std::fs::create_dir_all(git.join("rebase-merge")).unwrap();
        assert_eq!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Unchanged(path),
            "a rebase does not turn an idle no-op into a held-back write"
        );
    }

    #[test]
    fn regenerating_touches_nothing_inside_the_git_directory() {
        // PR #287 review, Test Quality #4: "never commit" was satisfied only by omission — no test
        // would have caught a future change that staged or committed the file. Committing is not
        // something this module can do without writing under `.git` (index, objects, refs, logs),
        // so the invariant is pinned as "the git directory comes out byte-identical".
        let tmp = TempDir::new().unwrap();
        let git = git_worktree(tmp.path());
        std::fs::write(git.join("HEAD"), b"ref: refs/heads/main\n").unwrap();
        std::fs::create_dir_all(git.join("objects")).unwrap();
        std::fs::write(git.join("index"), b"fake index").unwrap();

        let before = snapshot(&git);
        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        assert!(matches!(
            regenerate(&s, tmp.path()).unwrap(),
            Outcome::Written(_)
        ));
        assert!(
            tmp.path().join(FILE_NAME).is_file(),
            "the file itself landed"
        );
        assert_eq!(
            before,
            snapshot(&git),
            "the change belongs to the human: nothing is staged, nothing is committed"
        );
    }

    /// Every path under `dir` with its bytes — enough to notice a staged index, a new object, or a
    /// moved ref.
    fn snapshot(dir: &Path) -> Vec<(PathBuf, Vec<u8>)> {
        fn walk(dir: &Path, out: &mut Vec<(PathBuf, Vec<u8>)>) {
            let mut entries: Vec<_> = std::fs::read_dir(dir)
                .unwrap()
                .map(|e| e.unwrap().path())
                .collect();
            entries.sort();
            for path in entries {
                if path.is_dir() {
                    out.push((path.clone(), Vec::new()));
                    walk(&path, out);
                } else {
                    out.push((path.clone(), std::fs::read(&path).unwrap()));
                }
            }
        }
        let mut out = Vec::new();
        walk(dir, &mut out);
        out
    }

    // ---- the writer -----------------------------------------------------------------------

    #[cfg(unix)]
    #[test]
    fn the_write_refuses_a_pre_placed_temp_symlink_and_leaves_its_target_untouched() {
        // Mirrors the registry/heartbeat writers' own symlink test: the temp path is predictable,
        // so a symlink squatting on it must be refused rather than followed.
        use std::os::unix::fs::symlink;
        let tmp = TempDir::new().unwrap();
        let outside = tmp.path().join("precious.txt");
        std::fs::write(&outside, b"PRECIOUS").unwrap();
        symlink(
            &outside,
            tmp.path()
                .join(format!(".{FILE_NAME}.nxm.tmp.{}", std::process::id())),
        )
        .unwrap();

        let mut s = store();
        remember(&mut s, "auth", "auth uses JWT, not sessions");
        let err = regenerate(&s, tmp.path()).unwrap_err();
        assert_eq!(err.kind.as_str(), "io");
        assert_eq!(std::fs::read(&outside).unwrap(), b"PRECIOUS");
        assert!(!tmp.path().join(FILE_NAME).exists());
    }
}
